### ISSUE TITLE
About code not working

### ISSUE THREAD

**Issue by nlper01** [INK-USC/fewNER#4]
Hello, I need help, I can't run the code you provided on the Windows system, when I run the .py file after search.py (in the order of your file directory), it will report TypeError, in addition to score.py in Is line 14 code an editorial error? 
`from .utils import (
    get_model,
    get_tokenizer,
    get_idf_dict,
    bert_cos_score_idf,
    get_bert_embedding,
    lang2model,
    model2layers,
    get_hash,
    cache_scibert,
    sent_encode,
)Also, on the Ubuntu system, I did not run the code you provided, and the code file directory you provided is a bit complicated, can you explain a little bit?

**Comment by danny911kr** [comment]
Hi @FalAnge1217 , I highly recommend you to use conda environment.
Could you provide us the error message if it still gives you an error?

For the code structure, you may want to refer bash files in the `scripts` directory.

**Comment by danny911kr** [comment]
We'll close the issue. Please re-open it if it still the issue. Thanks.
